AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String

Resources:
  LogMonitor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "LogMonitor-${Env}"
      CodeUri: ./
      Runtime: python3.9
      Handler: function.handler
      Timeout: 30
      MemorySize: 256
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:DescribeLogGroups
                - logs:FilterLogEvents
              Resource: "*"
      Environment:
        Variables:
          ENV: !Ref Env
          HOOK_UUID: !Ref HookUuid
      Events:
        CronEvent:
          Type: Schedule
          Properties:
            Schedule: cron(*/5 * * * ? *)
            Name: !Sub "LogMonitorSchedule-${Env}"
            Description: Check recent logs every 5 minutes
